local CONST = MOAIParticleScript.packConst
local SCALE = 1.5
local r1 = MOAIParticleScript.packReg(1)
local init = MOAIParticleScript.new()
init:vecAngle(r1, MOAIParticleScript.PARTICLE_DX, MOAIParticleScript.PARTICLE_DY)
init:mul(r1, CONST(0.5), r1)
init:sub(r1, CONST(90), r1)
local render = MOAIParticleScript.new()
render:sprite()
render:set(MOAIParticleScript.SPRITE_ROT, r1)
render:mul(MOAIParticleScript.PARTICLE_X, MOAIParticleScript.PARTICLE_X, MOAIParticleScript.SPRITE_X_SCL)
render:mul(MOAIParticleScript.PARTICLE_Y, MOAIParticleScript.PARTICLE_Y, MOAIParticleScript.SPRITE_Y_SCL)
render:set(MOAIParticleScript.SPRITE_RED, CONST(0.3137254901960784))
render:set(MOAIParticleScript.SPRITE_GREEN, CONST(0.9411764705882353))
render:set(MOAIParticleScript.SPRITE_BLUE, CONST(1))
render:ease(MOAIParticleScript.SPRITE_OPACITY, CONST(0.8), CONST(0), MOAIEaseType.EASE_IN)
render:ease(MOAIParticleScript.SPRITE_GLOW, CONST(1), CONST(0.2), MOAIEaseType.SHARP_EASE_IN)
render:ease(MOAIParticleScript.SPRITE_X_SCL, CONST(0.6), CONST(1.5), MOAIEaseType.LINEAR)
render:set(MOAIParticleScript.SPRITE_Y_SCL, CONST(1.8), CONST(1.2), MOAIEaseType.SHARP_EASE_IN)
local system = ui.new(MOAIParticleSystem.new())
system:reserveParticles(512, 1)
system:reserveSprites(512)
system:reserveStates(2)
local state = MOAIParticleState.new()
state:setTerm(2.1, 2.1)
state:setInitScript(init)
state:setRenderScript(render)
system:setState(1, state)
local deck = resource.deck("ribbonTexture.png")
system:setDeck(deck)
local emitters = {}
local defaultEmitter = ui.new(MOAIParticleDistanceEmitter.new())
local w, h = resource.texture("ribbonTexture.png"):getSize()
defaultEmitter:setMagnitude(1)
defaultEmitter:setAngle(270, 270)
defaultEmitter:setDistance(w / 5 * SCALE)
defaultEmitter:setSystem(system)
system:add(defaultEmitter)
emitters[#emitters + 1] = defaultEmitter
system.emitters = emitters
return system
